/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "../../packages/ui/src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        homecafe: {
          pink: "#f691c3",
          "pink-light": "#ffe4e8",
          "pink-dark": "#e91e63",
          cream: "#fff8f0",
          beige: "#fdecce",
          green: "#04a056",
          "green-light": "#c8e6c9",
          orange: "#f46604",
          "orange-light": "#ffe0b2",
          blue: "#0062dd",
          yellow: "#fdcb08",
          grey: "#dadada",
          "grey-dark": "#7a7a7a",
        },
        mood: {
          calme: "#7CB9E8",
          enervement: "#E85454",
          excitation: "#FFD93D",
          anxiete: "#9CA3AF",
          tristesse: "#374151",
          bonheur: "#4ADE80",
          ennui: "#FB923C",
          nervosite: "#F472B6",
          productivite: "#A78BFA",
        },
        background: "#fffdfa",
        foreground: "#2b1e1c",
        card: "#ffffff",
        "card-foreground": "#2b1e1c",
        popover: "#ffffff",
        "popover-foreground": "#2b1e1c",
        primary: "#df005c",
        "primary-foreground": "#ffffff",
        secondary: "#f5eee0",
        "secondary-foreground": "#443734",
        muted: "#f5f1ea",
        "muted-foreground": "#696160",
        accent: "#ff9b50",
        "accent-foreground": "#2b1e1c",
        destructive: "#e7000b",
        "destructive-foreground": "#ffffff",
        success: "#31aa40",
        "success-foreground": "#ffffff",
        warning: "#ff9b50",
        "warning-foreground": "#2b1e1c",
        border: "#ebe4d6",
        input: "#f5f1ea",
        ring: "#df005c",
        "chart-1": "#31aa40",
        "chart-2": "#e7000b",
        "chart-3": "#df005c",
        "chart-4": "#ff9b50",
        "chart-5": "#7b3cf5",
        sidebar: "#f8f3ec",
        "sidebar-foreground": "#2b1e1c",
        "sidebar-primary": "#df005c",
        "sidebar-primary-foreground": "#ffffff",
        "sidebar-accent": "#f5e0e5",
        "sidebar-accent-foreground": "#443734",
        "sidebar-border": "#ebe4d6",
        "sidebar-ring": "#df005c",
      },
      borderRadius: {
        sm: "8px",
        md: "10px",
        lg: "12px",
        xl: "16px",
      },
    },
  },
  plugins: [],
};
