import type { achievementDefinition } from "../schema/reward";

type AchievementDefinitionSeed = typeof achievementDefinition.$inferInsert;

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinitionSeed[] = [
  {
    id: "ach-first-post",
    type: "sticker",
    key: "first-post",
    name: "Premier article",
    description: "Écris ton premier article",
    criteria: { eventType: "PostCreated", threshold: 1, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-first-mood",
    type: "sticker",
    key: "first-mood",
    name: "Première humeur",
    description: "Enregistre ton humeur pour la première fois",
    criteria: { eventType: "MoodRecorded", threshold: 1, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-first-photo",
    type: "sticker",
    key: "first-photo",
    name: "Première photo",
    description: "Publie ta première photo",
    criteria: { eventType: "PhotoUploaded", threshold: 1, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-first-moodboard",
    type: "sticker",
    key: "first-moodboard",
    name: "Premier moodboard",
    description: "Crée ton premier moodboard",
    criteria: {
      eventType: "MoodboardCreated",
      threshold: 1,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-first-friend",
    type: "sticker",
    key: "first-friend",
    name: "Premier ami",
    description: "Ajoute ton premier ami",
    criteria: {
      eventType: "FriendRequestAccepted",
      threshold: 1,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-journal-streak-7",
    type: "sticker",
    key: "journal-streak-7",
    name: "Série de 7 jours",
    description: "Écris dans ton journal 7 jours de suite",
    criteria: {
      eventType: "PostCreated",
      threshold: 7,
      field: "journalStreak",
    },
    iconUrl: null,
  },
  {
    id: "ach-journal-streak-14",
    type: "sticker",
    key: "journal-streak-14",
    name: "Série de 14 jours",
    description: "Écris dans ton journal 14 jours de suite",
    criteria: {
      eventType: "PostCreated",
      threshold: 14,
      field: "journalStreak",
    },
    iconUrl: null,
  },
  {
    id: "ach-posts-10",
    type: "sticker",
    key: "posts-10",
    name: "Conteur",
    description: "Écris 10 articles",
    criteria: { eventType: "PostCreated", threshold: 10, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-photos-10",
    type: "sticker",
    key: "photos-10",
    name: "Photographe",
    description: "Publie 10 photos",
    criteria: { eventType: "PhotoUploaded", threshold: 10, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-journal-streak-30",
    type: "badge",
    key: "journal-streak-30",
    name: "Série de 30 jours",
    description: "Écris dans ton journal 30 jours de suite",
    criteria: {
      eventType: "PostCreated",
      threshold: 30,
      field: "journalStreak",
    },
    iconUrl: null,
  },
  {
    id: "ach-posts-50",
    type: "badge",
    key: "posts-50",
    name: "Écrivain prolifique",
    description: "Écris 50 articles",
    criteria: { eventType: "PostCreated", threshold: 50, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-photos-50",
    type: "badge",
    key: "photos-50",
    name: "Pro de la photo",
    description: "Publie 50 photos",
    criteria: { eventType: "PhotoUploaded", threshold: 50, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-friends-5",
    type: "badge",
    key: "friends-5",
    name: "Sociable",
    description: "Ajoute 5 amis",
    criteria: {
      eventType: "FriendRequestAccepted",
      threshold: 5,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-friends-10",
    type: "badge",
    key: "friends-10",
    name: "Populaire",
    description: "Ajoute 10 amis",
    criteria: {
      eventType: "FriendRequestAccepted",
      threshold: 10,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-all-moods",
    type: "badge",
    key: "all-moods-recorded",
    name: "Arc-en-ciel",
    description: "Enregistre chaque catégorie d'humeur au moins une fois",
    criteria: {
      eventType: "MoodRecorded",
      threshold: 5,
      field: "uniqueMoodCategories",
    },
    iconUrl: null,
  },
  {
    id: "ach-kanban-master",
    type: "badge",
    key: "kanban-master",
    name: "Maître kanban",
    description: "Complète 10 cartes sur tes tableaux",
    criteria: {
      eventType: "CardCompleted",
      threshold: 10,
      field: "count",
    },
    iconUrl: null,
  },
];
