import type { achievementDefinition } from "../schema/reward";

type AchievementDefinitionSeed = typeof achievementDefinition.$inferInsert;

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinitionSeed[] = [
  {
    id: "ach-first-post",
    type: "sticker",
    key: "first-post",
    name: "First Post!",
    description: "Write your first post",
    criteria: { eventType: "PostCreated", threshold: 1, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-first-mood",
    type: "sticker",
    key: "first-mood",
    name: "First Mood!",
    description: "Record your first mood",
    criteria: { eventType: "MoodRecorded", threshold: 1, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-first-photo",
    type: "sticker",
    key: "first-photo",
    name: "First Photo!",
    description: "Upload your first photo",
    criteria: { eventType: "PhotoUploaded", threshold: 1, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-first-moodboard",
    type: "sticker",
    key: "first-moodboard",
    name: "First Moodboard!",
    description: "Create your first moodboard",
    criteria: {
      eventType: "MoodboardCreated",
      threshold: 1,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-first-friend",
    type: "sticker",
    key: "first-friend",
    name: "First Friend!",
    description: "Make your first friend",
    criteria: {
      eventType: "FriendRequestAccepted",
      threshold: 1,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-journal-streak-3",
    type: "sticker",
    key: "journal-streak-3",
    name: "3-Day Streak",
    description: "Write in your journal 3 days in a row",
    criteria: {
      eventType: "PostCreated",
      threshold: 3,
      field: "journalStreak",
    },
    iconUrl: null,
  },
  {
    id: "ach-journal-streak-7",
    type: "sticker",
    key: "journal-streak-7",
    name: "Week Warrior",
    description: "Write in your journal 7 days in a row",
    criteria: {
      eventType: "PostCreated",
      threshold: 7,
      field: "journalStreak",
    },
    iconUrl: null,
  },
  {
    id: "ach-mood-streak-7",
    type: "sticker",
    key: "mood-streak-7",
    name: "Mood Tracker",
    description: "Record your mood 7 days in a row",
    criteria: { eventType: "MoodRecorded", threshold: 7, field: "moodStreak" },
    iconUrl: null,
  },
  {
    id: "ach-mood-streak-30",
    type: "sticker",
    key: "mood-streak-30",
    name: "Mood Master",
    description: "Record your mood 30 days in a row",
    criteria: { eventType: "MoodRecorded", threshold: 30, field: "moodStreak" },
    iconUrl: null,
  },
  {
    id: "ach-posts-10",
    type: "sticker",
    key: "posts-10",
    name: "Storyteller",
    description: "Write 10 posts",
    criteria: { eventType: "PostCreated", threshold: 10, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-photos-10",
    type: "sticker",
    key: "photos-10",
    name: "Shutterbug",
    description: "Upload 10 photos",
    criteria: { eventType: "PhotoUploaded", threshold: 10, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-journal-streak-30",
    type: "badge",
    key: "journal-streak-30",
    name: "Journal Devotee",
    description: "Write in your journal 30 days in a row",
    criteria: {
      eventType: "PostCreated",
      threshold: 30,
      field: "journalStreak",
    },
    iconUrl: null,
  },
  {
    id: "ach-mood-streak-60",
    type: "badge",
    key: "mood-streak-60",
    name: "Zen Master",
    description: "Record your mood 60 days in a row",
    criteria: { eventType: "MoodRecorded", threshold: 60, field: "moodStreak" },
    iconUrl: null,
  },
  {
    id: "ach-posts-50",
    type: "badge",
    key: "posts-50",
    name: "Prolific Writer",
    description: "Write 50 posts",
    criteria: { eventType: "PostCreated", threshold: 50, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-photos-50",
    type: "badge",
    key: "photos-50",
    name: "Photographer",
    description: "Upload 50 photos",
    criteria: { eventType: "PhotoUploaded", threshold: 50, field: "count" },
    iconUrl: null,
  },
  {
    id: "ach-friends-5",
    type: "badge",
    key: "friends-5",
    name: "Social Butterfly",
    description: "Make 5 friends",
    criteria: {
      eventType: "FriendRequestAccepted",
      threshold: 5,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-friends-10",
    type: "badge",
    key: "friends-10",
    name: "Popular",
    description: "Make 10 friends",
    criteria: {
      eventType: "FriendRequestAccepted",
      threshold: 10,
      field: "count",
    },
    iconUrl: null,
  },
  {
    id: "ach-all-moods",
    type: "badge",
    key: "all-moods-recorded",
    name: "Emotional Rainbow",
    description: "Record every mood category at least once",
    criteria: {
      eventType: "MoodRecorded",
      threshold: 5,
      field: "uniqueMoodCategories",
    },
    iconUrl: null,
  },
  {
    id: "ach-kanban-master",
    type: "badge",
    key: "kanban-master",
    name: "Kanban Master",
    description: "Complete 10 cards on your boards",
    criteria: {
      eventType: "CardCompleted",
      threshold: 10,
      field: "count",
    },
    iconUrl: null,
  },
];
